### ISSUE TITLE
Duplicated resource name

### ISSUE THREAD

**Issue by aguilarguisado** [henrytao-me/android-md-core#38]
Hi there!

Your lib seems to be amazing but I'm not able to use it.

I need to update to buildTools 23.0.1 because of other dependencies and while building the APK, it seems like there is a duplicated resource name:

Error:(2) Attribute "md_background_color" has already been defined

I found a "md_background_color" in your resource files. Maybe refactoring this name could be the solution, but I'm not sure.

Thank you for sharing your work. OpenSource makes us free.

**Comment by henrytao-me** [comment]
Hi @juaagugui,
Thanks for your feedback. I will upgrade buildTools to 23.0.1 some day this week. Also, I am working on version 2.0 which is kind of `Material in action`. Look promising. Stay tuned.

**Comment by henrytao-me** [comment]
Hi @juaagugui, version `1.x` is deprecated. I will close this ticket and will ping you when version 2.0 is released. ;)

**Comment by aguilarguisado** [comment]
Hi @henrytao-me , thank you so much !! I'll try your library ASAP, because as I told you it seems to be potentially useful.
