### ISSUE TITLE
Runtime exception

### ISSUE THREAD

**Issue by ddmmcjmm** [henrytao-me/android-md-core#57]
Hi,

I really like the idea of this library. I added the library like this:

```
compile "me.henrytao:mdcore:1.9.7"
```

But there is this run-time exception:

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.testapp/com.example.testapp.MainActivity}: android.view.InflateException: Binary XML file line #29: Error inflating class TextView
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2345)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2405)
            at android.app.ActivityThread.access$800(ActivityThread.java:149)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1324)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:211)
            at android.app.ActivityThread.main(ActivityThread.java:5317)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1016)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
```

Thanks for helping.

**Comment by henrytao-me** [comment]
Hi @ddmmcjmm 

Thanks for your interest in this library. I haven't released version 2.0 yet. There are somethings pretty cool here. Especially, it supports attribute color in selector, back port to API 11. I also sent a PR to android team here [PR for supporting attribute](https://github.com/android/platform_frameworks_base/pull/84)

Regard to your issue, I guess you haven't setup the theme properly. Your app theme has to be extend from either `MdTheme.Light` or `MdTheme.Dark`. Check out here [Sample code](https://github.com/henrytao-me/android-md-core/blob/master/sample%2Fsrc%2Fmain%2Fres%2Fvalues%2Fthemes.xml#L23)

I hope it helps.

**Comment by ddmmcjmm** [comment]
Thanks Henry.

Changing my app theme to extend `MdTheme.Light` works. There is now no more runtime exception. I copied from the sample [fragment_list](https://github.com/henrytao-me/android-md-core/blob/master/sample/src/main/res/layout/fragment_list.xml) to my code but the result looks like this ![screenshot](http://i64.tinypic.com/2cwl6yp.png)

It would be nice if you can tell me how to get the ActionBar back after extending the `MdTheme.Light`. I think your library is meaningful in the way that it provides an easy way for people who are afraid of tinkering with styles/dimens/themes to conform to the material design guideline. I look forward to your 2.0 version (along with some usage in the readme, of course:)). Thanks so much for taking the time to create md-core.

**Comment by henrytao-me** [comment]
Hi, 
This issue is related to layout (RelativeLayout has a child with AlignParentBottom). 
Both light and dark theme in `mdcore` are extended from `NoActionBar` theme. You have to use Toolbar instead. So, they way it works are: 
- Using proper theme (light or dark)
- Override color palette to match your app style
- Declare toolbar in your activity layout
- You are using ListItem. It should be inside scrollView, listView or recyclerView. So that, it won't be expanded fullscreen like that. 

Documentation is something definitely much to have for this kind of library. I will update it soon.
