### ISSUE TITLE
Preserving colour of drawable when setting avatar and icon

### ISSUE THREAD

**Issue by nikoladoherty** [henrytao-me/android-md-core#60]
Hi @henrytao-me,

This seems to be a great lib. Something that Google should've done to encourage the adoption of material design. I tried to put drawables into the avatar and icon of MdListItem. But they are all turned dark when I use the MdTheme.Light and they are all turned light when I use the MdTheme.Dark. How do I keep the original colour of the drawable the way the avatars in the Gmail app works? It seems that there is a MdIcon tint and some other icon colours in the source. What should I override in my theme that extends MdTheme?

 I think this library will attract a lot more attention once you have more documentation. Thank you.

Niko

**Comment by henrytao-me** [comment]
Hi Niko,

If you want to keep original color of the drawable, you can custom MdListItem and use ImageView instead of MdIcon.

**Comment by henrytao-me** [comment]
I will update list examples later. Thanks for your interest in this library. ;). I love it.

**Comment by henrytao-me** [comment]
Hi @nikoladoherty 
Please check out `v1.9.10`. I updated iconTintMode for list item. You raised a very good point where MdListItem shouldn't apply tint mode for avatar. In your case, if you want to keep icon color, you can declare view like this:

```
<me.henrytao.mdcore.widgets.MdListItem
      android:layout_width="match_parent"
      android:layout_height="wrap_content"
      android:background="?attr/selectableItemBackground"
      android:clickable="true"
      app:mdli_divider_layout="@layout/mdli_divider_left"
      app:mdli_icon="@drawable/ic_blank_circle"
      app:mdli_icon_tintMode="dst"
      app:mdli_title="@string/text_single_line_item"
      app:mdli_type="single_line_icon_with_text" />
```

**Comment by nikoladoherty** [comment]
Thanks for the update! The avatar now shows colour. Thanks for also implementing the icon tint mode attribute.
