### ISSUE TITLE
How to use MdIconToggle

### ISSUE THREAD

**Issue by Alxzu** [henrytao-me/android-md-core#73]
Hi, I'm currently trying to use, without success, some MdIconToggle but I'm getting 
**Error:(34, 29) No resource found that matches the given name (at 'button' with value '@drawable/ic_menu_favorite').** 
when I try to compile

```
<me.henrytao.mdcore.widgets.MdIconToggle
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:button="@drawable/ic_menu_favorite"
            android:layout_gravity="left|center_vertical"/>
```

any ideas? Thank you very much

**Comment by henrytao-me** [comment]
Can you try to use your own drawable?

**Comment by Alxzu** [comment]
That work but I'm getting **Error inflating class me.henrytao.mdcore.widgets.MdIconToggle** 

```
<me.henrytao.mdcore.widgets.MdIconToggle
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:button="@drawable/ic_favorite_white_24dp"
        android:layout_gravity="left|center_vertical"/>
```

do I need to provide some kind of wrapper to mdIconToggle?

**Comment by henrytao-me** [comment]
Are you putting it as a root node in your layout file?

**Comment by Alxzu** [comment]
```
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    xmlns:app="http://schemas.android.com/apk/res-auto">

    <com.flaviofaria.kenburnsview.KenBurnsView
        android:id="@+id/backdrop"
        android:layout_width="match_parent"
        android:layout_height="256dp"
        android:scaleType="centerCrop"
        app:layout_collapseMode="parallax" />

    <de.hdodenhof.circleimageview.CircleImageView
        xmlns:android="http://schemas.android.com/apk/res/android"
        android:id="@+id/profile_image"
        android:layout_width="96dp"
        android:layout_height="96dp"
        android:src="@drawable/default_avatar"
        android:layout_gravity="center"
        android:layout_centerVertical="true"
        android:layout_centerHorizontal="true" />


    <me.henrytao.mdcore.widgets.MdIconToggle
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:button="@drawable/ic_favorite_white_24dp"
        android:layout_gravity="left|center_vertical"/>


</FrameLayout>
```

**Comment by Alxzu** [comment]
buy the way I'm usign 
_compile 'me.henrytao:mdcore:1.9.11'_

**Comment by henrytao-me** [comment]
It should work normally (I think). Can you try to remove `layout_gravity`? If removing it work, it means it has a bug. I need to fix it.

**Comment by Alxzu** [comment]
It doen't work, at the bottom of the stack it says:
_Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v7/internal/widget/ViewUtils;
                                                                    at me.henrytao.mdcore.widgets.MdIconToggle.isLayoutRtl(MdIconToggle.java:147)
                                                                    at me.henrytao.mdcore.widgets.MdIconToggle.invalidatePadding(MdIconToggle.java:139)
                                                                    at me.henrytao.mdcore.widgets.MdIconToggle.initFromAttributes(MdIconToggle.java:100)
                                                                    at me.henrytao.mdcore.widgets.MdIconToggle.<init>(MdIconToggle.java:_

**Comment by henrytao-me** [comment]
It's kind of weird. I compiled and ran successful with this layout in my sample project. 

```
  <FrameLayout
      android:layout_width="match_parent"
      android:layout_height="wrap_content">

      <me.henrytao.mdcore.widgets.MdIconToggle
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="left|center_vertical"
        android:button="@drawable/ic_menu_favorite" />
    </FrameLayout>
```

Can you profile more information about your project configurations? 
Mine is 

```
compileSdkVersion: 23,
buildToolsVersion: "23.0.1",
minSdkVersion    : 8,
targetSdkVersion : 23,
```

**Comment by Alxzu** [comment]
compileSdkVersion: 23,
buildToolsVersion: "23.0.2",
minSdkVersion    : 16,
targetSdkVersion : 23

I'm using Android Studio 2.0 Preview 5

**Comment by henrytao-me** [comment]
Interesting. I am also using Android Studio 2.0 Preview 5. I just upgraded buildToolsVersion to 23.0.2. It still works normally. If it's possible, would you mind add me as a collaborator to your project or we can schedule a teamviewer sometime to investigate this issue?

In the meantime, can you try to clean build, invalidate cache and retry again?
