### ISSUE TITLE
MdListItem any way to get item to wrap context?

### ISSUE THREAD

**Issue by Alxzu** [henrytao-me/android-md-core#74]
Hi, I need to use some kind of wrapper for my "comments" but my problem is content use to be around 160 characters, so I need the layout to grown to wrap it, any way to achive this? thank you so much, any help will be appreciated

**Comment by henrytao-me** [comment]
Can you send me your current implementation (layout)? I will start suggesting from it.

**Comment by Alxzu** [comment]
Using [https://github.com/henrytao-me/android-md-core/blob/master/sample%2Fsrc%2Fmain%2Fres%2Flayout%2Factivity_list.xml#L600](url) to create a custom layout. Thanks
