### ISSUE TITLE
Handle icon on click

### ISSUE THREAD

**Issue by Alxzu** [henrytao-me/android-md-core#75]
How can achive handle MdItem on right icon onClick? Thanks I love this library

<img width="380" alt="captura de pantalla 2016-02-14 a las 1 33 06 p m" src="https://cloud.githubusercontent.com/assets/8084303/13034837/85575dd2-d31f-11e5-8a33-7993a303bd48.png">

**Comment by henrytao-me** [comment]
Hi @Alxzu, 

You can use this `mMdListItem.findViewById(android.R.id.icon2)`. However, I should provide listeners for left avatar and right icon. 

Thanks for using this library. I love to hear more feedback from you. 

Cheers, 
Henry

**Comment by Alxzu** [comment]
Hi, thank you very much for your help, it worked like a charm!
