### ISSUE TITLE
Make Avatar a circle image view

### ISSUE THREAD

**Issue by Alxzu** [henrytao-me/android-md-core#76]
Hi, me again, sorry to bother you. Is there any simple way to cast image view to be circle as it's shown in your demo?

![captura de pantalla 2016-02-15 a las 6 54 57 p m](https://cloud.githubusercontent.com/assets/8084303/13061252/a3ec9b8a-d415-11e5-943c-4369771c6f67.png)

![captura de pantalla 2016-02-15 a las 6 55 33 p m](https://cloud.githubusercontent.com/assets/8084303/13061272/b931c1f0-d415-11e5-9c55-141a206488c6.png)

**Comment by henrytao-me** [comment]
Hi @Alxzu 

For circle images, please consider to use fresco and custom layout like this [Custom MdListItem Layout](https://github.com/henrytao-me/android-md-core/blob/master/sample%2Fsrc%2Fmain%2Fres%2Flayout%2Factivity_list.xml#L600).

**Comment by Alxzu** [comment]
Thank you, I'm using [https://github.com/hdodenhof/CircleImageView](url) for circle images along with Picasso. Thanks again for your help
