### ISSUE TITLE
java.lang.IllegalArgumentException: Crashlytics found an invalid API key: null. 

### ISSUE THREAD

**Issue by jiqimaogou** [henrytao-me/android-md-core#85]
:sample:fabricGenerateResourcesDebug
ERROR - Crashlytics Developer Tools error.
java.lang.IllegalArgumentException: Crashlytics found an invalid API key: null. 
Check the Crashlytics plugin to make sure that the application has been added successfully! 
Contact support@fabric.io for assistance.

**Comment by henrytao-me** [comment]
I disabled fabric in sample module. Please check it out again @jiqimaogou
