### ISSUE TITLE
help

### ISSUE THREAD

**Issue by gonza28** [henrytao-me/android-md-core#94]
Hi. Thank you very much for your work.
because they do not have this problem

http://i.imgur.com/kg064oV.png

**Comment by henrytao-me** [comment]
What do you mean? @gonza28 
It's lambda. You need to install Java8. Hmmmmmmmmm. Let me know if you still have this problem.

**Comment by gonza28** [comment]
I tried again today and I can not solve.
Lambada is new to me.

http://i.imgur.com/7z6l8Ss.png
http://i.imgur.com/B6N88kD.png
http://i.imgur.com/bRJ1iBP.png
http://i.imgur.com/vOoYhlG.png
